"""
Fine-tune Laya on traffic-signal decisions generated by the ARTERIA simulator.

    python server/finetune_traffic.py

Why this is needed: the shipped checkpoint has never seen a traffic decision.
Measured zero-shot on this domain it answered the same road regardless of the
state — which matches Laya's own figure of 0.362 accuracy zero-shot against
0.766 fine-tuned on its typed-decisions benchmark.

The dataset comes from `tools/make_dataset.mjs`. Each row pairs the NOISY camera
description the live controller actually sees with a label computed from the
simulator's GROUND TRUTH, so the model learns to infer the true state of a
junction from an imperfect description of it.

Training follows Laya's own recipe (RLCD: GRPO against a strictly proper scoring
rule, plus soft cross-entropy), adapted from their 2xT4 DDP notebook to a single
local GPU.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
import time

import torch
from safetensors.torch import load_file, save_file
from transformers import AutoTokenizer
from huggingface_hub import snapshot_download

from laya.common import build_model, proper_reward, build_sequence, render_options, QTYPES

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRAIN_JSONL = os.path.join(ROOT, "data", "traffic_decisions.jsonl")
OUTPUT_DIR = os.path.join(ROOT, "models", "laya-arteria")
BASE_MODEL = os.environ.get("ARTERIA_BASE_MODEL", "convaiinnovations/laya")

EPOCHS = int(os.environ.get("ARTERIA_EPOCHS", "3"))
MICRO_BATCH = int(os.environ.get("ARTERIA_MICRO_BATCH", "8"))
GRAD_ACCUM = int(os.environ.get("ARTERIA_GRAD_ACCUM", "8"))
GROUP_SIZE = 4
LR_ENCODER = 2.5e-5
LR_HEAD = 1.0e-4
SIGMA_START, SIGMA_END = 0.4, 0.1
CALIB_MAX = 400
LIMIT = int(os.environ.get("ARTERIA_LIMIT", "0")) or None

# How many of the encoder's top layers to train, plus the head. The full 421M
# model with AdamW's two moment buffers needs ~8.5 GB before activations, which
# overflows an 8 GB card and spills to system memory over PCIe - the run does
# not fail, it just crawls. Training the top slice keeps everything resident.
TRAIN_TOP = int(os.environ.get("ARTERIA_TRAIN_TOP_LAYERS", "8"))
GRAD_CKPT = os.environ.get("ARTERIA_GRAD_CKPT", "0") == "1"


def freeze_lower(model, keep_top):
    """Freeze the embeddings and every encoder layer below the top `keep_top`."""
    import re
    idxs = {int(m.group(1)) for n, _ in model.named_parameters()
            if (m := re.match(r"encoder\.layers\.(\d+)\.", n))}
    if not idxs or keep_top <= 0:
        return sum(p.numel() for p in model.parameters()), 0
    n_layers = max(idxs) + 1
    cutoff = max(0, n_layers - keep_top)
    trainable = frozen = 0
    for n, p in model.named_parameters():
        m = re.match(r"encoder\.layers\.(\d+)\.", n)
        low = n.startswith("encoder.embeddings.") or (m and int(m.group(1)) < cutoff)
        p.requires_grad = not low
        if low:
            frozen += p.numel()
        else:
            trainable += p.numel()
    print(f"  encoder has {n_layers} layers; training the top {keep_top} plus the head")
    print(f"  trainable {trainable/1e6:.1f}M, frozen {frozen/1e6:.1f}M")
    return frozen, trainable


# ---------------------------------------------------------------------------
def collate(items, pad_id):
    n = len(items)
    L = max(len(it["ids"]) for it in items)
    kmax = max(len(it["markers"]) for it in items)
    ids = torch.full((n, L), pad_id, dtype=torch.long)
    att = torch.zeros((n, L), dtype=torch.long)
    mpos = torch.zeros((n, kmax), dtype=torch.long)
    mmask = torch.zeros((n, kmax), dtype=torch.bool)
    target = torch.zeros((n, kmax), dtype=torch.float32)
    for i, it in enumerate(items):
        ids[i, : len(it["ids"])] = torch.tensor(it["ids"])
        att[i, : len(it["ids"])] = 1
        k = len(it["markers"])
        mpos[i, :k] = torch.tensor(it["markers"])
        mmask[i, :k] = True
        target[i, : len(it["target"])] = torch.tensor(it["target"], dtype=torch.float32)
    return {
        "input_ids": ids, "attention_mask": att, "marker_pos": mpos,
        "marker_mask": mmask, "target": target,
        "qtype": torch.tensor([it["qtype"] for it in items]),
    }


def fit_one_temp(sel):
    if len(sel) < 10:
        return 1.0
    kmax = max(len(z) for z, _ in sel)
    Z = torch.full((len(sel), kmax), -1e4)
    T = torch.zeros((len(sel), kmax))
    for i, (z, t) in enumerate(sel):
        Z[i, : len(z)] = torch.tensor(z)
        T[i, : len(t)] = torch.tensor(t, dtype=torch.float32)
    log_t = torch.zeros(1, requires_grad=True)
    opt = torch.optim.LBFGS([log_t], lr=0.1, max_iter=100)

    def closure():
        opt.zero_grad()
        loss = -(T * torch.log_softmax(Z / log_t.exp(), -1)).sum(-1).mean()
        loss.backward()
        return loss

    opt.step(closure)
    return float(torch.clamp(log_t.exp(), 0.1, 10.0).item())


def build_items(path, tok, cfg, limit=None):
    """Turn the JSONL rows into tokenised training items, one per question."""
    items = []
    skipped = 0
    with open(path, encoding="utf-8") as fh:
        for ln, line in enumerate(fh):
            if limit and len(items) >= limit:
                break
            row = json.loads(line)
            state = json.loads(row["state"])
            questions = json.loads(row["questions"])
            gold = json.loads(row["gold"])
            for qid, q in questions.items():
                g = gold.get(qid)
                if not g:
                    continue
                t = q["type"]
                crit = q.get("criteria", {})
                if t == "choice":
                    keys = list(crit.keys())
                    target = [g["probabilities"].get(k, 0.0) for k in keys]
                elif t == "noul":
                    target = [g["probabilities"].get("false", 0.5),
                              g["probabilities"].get("true", 0.5)]
                else:
                    n_levels = len(crit) if isinstance(crit, list) else 4
                    target = [g["probabilities"].get(str(i), 0.0) for i in range(n_levels)]
                s = sum(target)
                target = [v / s for v in target] if s > 0 else [1.0 / len(target)] * len(target)

                k = len(render_options({"t": t, "crit": crit}))
                seq, markers = build_sequence(
                    tok, state, {"t": t, "ins": q["instructions"], "crit": crit},
                    cfg["max_len"], cfg["head_max_len"])
                if len(markers) != k:
                    skipped += 1
                    continue
                items.append({
                    "ids": seq, "markers": markers, "qtype": QTYPES[t],
                    "target": target, "label": target.index(max(target)),
                })
    if skipped:
        print(f"  skipped {skipped} malformed items")
    return items


# ---------------------------------------------------------------------------
def main():
    if not torch.cuda.is_available():
        print("ERROR: no CUDA device. Training this on CPU is not practical.")
        print("Install a GPU build of torch that matches your card, then retry.")
        sys.exit(1)
    if not os.path.exists(TRAIN_JSONL):
        print(f"ERROR: {TRAIN_JSONL} not found.")
        print("Generate it first:  node tools/make_dataset.mjs 3000")
        sys.exit(1)

    device = torch.device("cuda", 0)
    torch.cuda.set_device(0)
    print("GPU:", torch.cuda.get_device_name(0))

    print(f"downloading base checkpoint {BASE_MODEL} ...")
    model_dir = snapshot_download(BASE_MODEL)
    with open(os.path.join(model_dir, "rl_agent_config.json")) as f:
        cfg = json.load(f)
    cfg["gradient_checkpointing"] = GRAD_CKPT
    cfg["max_tokens_per_batch"] = 4096
    cfg["max_len"] = 1024
    cfg["head_max_len"] = 256

    tok = AutoTokenizer.from_pretrained(os.path.join(model_dir, "tokenizer"))

    print("tokenising dataset ...")
    all_items = build_items(TRAIN_JSONL, tok, cfg, limit=LIMIT)
    print(f"  {len(all_items)} training sequences")

    order = list(range(len(all_items)))
    random.Random(20260927).shuffle(order)
    n_calib = min(CALIB_MAX, len(all_items) // 10)
    calib_items = [all_items[i] for i in sorted(order[:n_calib])]
    train_items = [all_items[i] for i in sorted(order[n_calib:])]
    print(f"  {len(train_items)} train / {len(calib_items)} held out for calibration")

    model = build_model(cfg, encoder_dir=os.path.join(model_dir, "encoder"))
    model.load_state_dict(load_file(os.path.join(model_dir, "model.safetensors")), strict=True)
    freeze_lower(model, TRAIN_TOP)
    if GRAD_CKPT:
        model.encoder.gradient_checkpointing_enable(
            gradient_checkpointing_kwargs={"use_reentrant": False})
        model.head_checkpointing = True
    model.to(device)
    model.train()

    enc = [p for n, p in model.named_parameters() if "encoder." in n and p.requires_grad]
    head = [p for n, p in model.named_parameters() if "encoder." not in n and p.requires_grad]
    optimizer = torch.optim.AdamW(
        [{"params": enc, "lr": LR_ENCODER}, {"params": head, "lr": LR_HEAD}],
        weight_decay=0.01)
    total_updates = max(1, (len(train_items) // (MICRO_BATCH * GRAD_ACCUM)) * EPOCHS)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=total_updates, eta_min=1e-6)
    scaler = torch.amp.GradScaler("cuda", enabled=True)

    print(f"training {EPOCHS} epochs, effective batch {MICRO_BATCH * GRAD_ACCUM}")
    t0 = time.time()

    for epoch in range(EPOCHS):
        random.seed(42 + epoch)
        random.shuffle(train_items)
        epoch_loss, n_batches, accum = 0.0, 0, 0
        optimizer.zero_grad(set_to_none=True)
        sigma = SIGMA_START + (SIGMA_END - SIGMA_START) * (epoch / max(1, EPOCHS - 1))

        for b in range(0, len(train_items), MICRO_BATCH):
            chunk = train_items[b:b + MICRO_BATCH]
            if not chunk:
                continue
            batch = collate(chunk, tok.pad_token_id)

            with torch.autocast("cuda", dtype=torch.float16):
                logits, act = model(
                    batch["input_ids"].to(device), batch["attention_mask"].to(device),
                    batch["marker_pos"].to(device), batch["marker_mask"].to(device),
                    batch["qtype"].to(device))

            logits = logits.float()
            mask = batch["marker_mask"].to(device)
            k = mask.sum(-1, keepdim=True).float()
            target = batch["target"].to(device)

            eps = torch.randn((GROUP_SIZE,) + logits.shape, device=device) * sigma * mask
            eps = (eps - eps.sum(-1, keepdim=True) / k) * mask
            z = logits.detach().unsqueeze(0) + eps
            q = torch.softmax(z.masked_fill(~mask, -1e4), -1)

            with torch.no_grad():
                r = proper_reward(q, target.unsqueeze(0), batch["qtype"].to(device),
                                  mask, w_sph=0.75, w_rps=1.0)
                adv = r - r.mean(0, keepdim=True)
                adv = adv / (adv.std() + 1e-6)

            logp = -(((z - logits.unsqueeze(0)) ** 2) * mask).sum(-1) / (2 * sigma ** 2)
            loss_rl = -(adv * logp).mean()
            loss_ce = -(target * torch.log_softmax(logits.masked_fill(~mask, -1e4), -1)).sum(-1).mean()
            loss = (loss_rl + 1.0 * loss_ce) / GRAD_ACCUM + 0.0 * act.sum()

            scaler.scale(loss).backward()
            accum += 1
            if accum % GRAD_ACCUM == 0 or (b + MICRO_BATCH) >= len(train_items):
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1.0)
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                optimizer.zero_grad(set_to_none=True)

            epoch_loss += loss.item() * GRAD_ACCUM
            n_batches += 1
            if n_batches % 50 == 0:
                done = b + MICRO_BATCH
                print(f"  epoch {epoch+1}/{EPOCHS} {done}/{len(train_items)} "
                      f"loss {loss.item()*GRAD_ACCUM:.4f} reward {r.mean().item():.3f} "
                      f"lr {scheduler.get_last_lr()[0]:.2e} "
                      f"[{time.time()-t0:.0f}s]")

        print(f"=== epoch {epoch+1}/{EPOCHS} done in {time.time()-t0:.0f}s, "
              f"avg loss {epoch_loss/max(1,n_batches):.4f} ===")

        ckpt = os.path.join(OUTPUT_DIR, "checkpoint_latest")
        os.makedirs(ckpt, exist_ok=True)
        save_file({k2: v.half().contiguous().cpu() for k2, v in model.state_dict().items()},
                  os.path.join(ckpt, "model.safetensors"))
        model.encoder.config.save_pretrained(os.path.join(ckpt, "encoder"))
        tok.save_pretrained(os.path.join(ckpt, "tokenizer"))

    # ---- calibration -------------------------------------------------------
    print("\nfitting calibration temperatures ...")
    del optimizer, scaler, scheduler
    torch.cuda.empty_cache()
    model.eval()
    preds = []
    with torch.no_grad():
        for c in range(0, len(calib_items), 16):
            chunk = calib_items[c:c + 16]
            cb = collate(chunk, tok.pad_token_id)
            with torch.autocast("cuda", dtype=torch.float16):
                l, _ = model(cb["input_ids"].to(device), cb["attention_mask"].to(device),
                             cb["marker_pos"].to(device), cb["marker_mask"].to(device),
                             cb["qtype"].to(device))
            ln = l.float().cpu().numpy()
            for i, it in enumerate(chunk):
                preds.append((it["qtype"], ln[i, : len(it["markers"])], it["target"]))

    temps = [1.2, 1.2, 1.2]
    try:
        for qt in range(3):
            sel = [(z, t) for qtype, z, t in preds if qtype == qt]
            if sel:
                temps[qt] = fit_one_temp(sel)
        print("temperatures (choice, score, noul):", [round(t, 3) for t in temps])
    except Exception as e:
        print("temperature fitting fallback:", e)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    save_file({k2: v.half().contiguous().cpu() for k2, v in model.state_dict().items()},
              os.path.join(OUTPUT_DIR, "model.safetensors"))
    model.encoder.config.save_pretrained(os.path.join(OUTPUT_DIR, "encoder"))
    tok.save_pretrained(os.path.join(OUTPUT_DIR, "tokenizer"))
    cfg["fine_tuned"] = True
    cfg["model_name"] = "laya-arteria"
    cfg["temperature"] = temps
    cfg.pop("temperature_by_options", None)
    with open(os.path.join(OUTPUT_DIR, "rl_agent_config.json"), "w") as f:
        json.dump(cfg, f, indent=2)
    print("saved ->", OUTPUT_DIR)


if __name__ == "__main__":
    main()
